#!/bin/bash

make

avr-gcc -c -mmcu=atmega32u4 -gdwarf-2 -DF_CPU=8000000UL -DPROTOCOL_PJRC -DBOOTMAGIC_ENABLE -DEXTRAKEY_ENABLE -DCONSOLE_ENABLE -DCOMMAND_ENABLE -DBACKLIGHT_ENABLE -DVERSION=eba9cd3-dirty -Os -funsigned-char -funsigned-bitfields -ffunction-sections -fdata-sections -fno-inline-small-functions -fpack-struct -fshort-enums -fno-strict-aliasing -Wall -Wstrict-prototypes -Wa,-adhlns=obj_c44/common/avr/eeconfig.lst -I. -I../../tmk_core -I../../tmk_core/protocol/pjrc -I../../tmk_core/common -std=gnu99 -include config.h -MMD -MP -MF .dep/obj_lightsaber_pjrc_common_avr_eeconfig.o.d  ../../tmk_core/common/avr/eeconfig.c -o obj_c44/common/avr/eeconfig.o

avr-gcc -mmcu=atmega32u4 -gdwarf-2 -DF_CPU=16000000UL -DINTERRUPT_CONTROL_ENDPOINT -DBOOTLOADER_SIZE=4096 -DMOUSEKEY_ENABLE -DMOUSE_ENABLE -DEXTRAKEY_ENABLE -DNO_PRINT -DNO_DEBUG -DBACKLIGHT_ENABLE -DVERSION=eba9cd3 -DF_USB=16000000UL -DARCH=ARCH_AVR8 -DUSB_DEVICE_ONLY -DUSE_FLASH_DESCRIPTORS -DUSE_STATIC_OPTIONS="(USB_DEVICE_OPT_FULLSPEED | USB_OPT_REG_ENABLED | USB_OPT_AUTO_PLL)" -DFIXED_CONTROL_ENDPOINT_SIZE=8  -DFIXED_NUM_CONFIGURATIONS=1 -DPROTOCOL_LUFA -Os -funsigned-char -funsigned-bitfields -ffunction-sections -fdata-sections -fno-inline-small-functions -fpack-struct -fshort-enums -fno-strict-aliasing -Wall -Wstrict-prototypes -Wa,-adhlns=c44.elf -I. -I../../tmk_core -I../../tmk_core/common -I../../tmk_core/protocol -I../../tmk_core/protocol/lufa -I../../tmk_core/protocol/lufa/LUFA-git -std=gnu99 -include config.h -MMD -MP -MF .dep/c44.elf.d  obj_c44/keymap.o obj_c44/keymap_common.o obj_c44/matrix.o obj_c44/i2c-master.o obj_c44/i2c-slave.o obj_c44/serial.o obj_c44/c44-util.o obj_c44/main.o obj_c44/led.o obj_c44/backlight.o obj_c44/common/host.o obj_c44/common/keyboard.o obj_c44/common/action.o obj_c44/common/action_tapping.o obj_c44/common/action_macro.o obj_c44/common/action_layer.o obj_c44/common/action_util.o obj_c44/common/keymap.o obj_c44/common/print.o obj_c44/common/debug.o obj_c44/common/util.o obj_c44/common/avr/suspend.o obj_c44/common/avr/xprintf.o obj_c44/common/avr/timer.o obj_c44/common/avr/bootloader.o obj_c44/common/mousekey.o obj_c44/common/backlight.o obj_c44/protocol/lufa/lufa.o obj_c44/protocol/lufa/descriptor.o obj_c44/protocol/lufa/LUFA-git/LUFA/Drivers/USB/Class/Common/HIDParser.o obj_c44/protocol/lufa/LUFA-git/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.o obj_c44/protocol/lufa/LUFA-git/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.o obj_c44/protocol/lufa/LUFA-git/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.o obj_c44/protocol/lufa/LUFA-git/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.o obj_c44/protocol/lufa/LUFA-git/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.o obj_c44/protocol/lufa/LUFA-git/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.o obj_c44/protocol/lufa/LUFA-git/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.o obj_c44/protocol/lufa/LUFA-git/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.o obj_c44/protocol/lufa/LUFA-git/LUFA/Drivers/USB/Core/ConfigDescriptors.o obj_c44/protocol/lufa/LUFA-git/LUFA/Drivers/USB/Core/DeviceStandardReq.o obj_c44/protocol/lufa/LUFA-git/LUFA/Drivers/USB/Core/Events.o obj_c44/protocol/lufa/LUFA-git/LUFA/Drivers/USB/Core/HostStandardReq.o obj_c44/protocol/lufa/LUFA-git/LUFA/Drivers/USB/Core/USBTask.o obj_c44/common/avr/eeconfig.o --output c44.elf -Wl,-Map=c44.map,--cref -Wl,--gc-sections     -lm 

make
